services:
  - type: web
    name: sistema-vendas
    runtime: docker
    plan: free
    branch: feature/v2-spring-boot
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_DB_PASSWORD
        sync: false
