services:
  - type: web
    name: sistema-vendas
    runtime: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    healthCheckPath: /api/produtos
    envVars:
      - key: SUPABASE_DB_PASSWORD
        sync: false
