spring.application.name=sistema-vendas

# 1. Configurações de Conexão com o Banco H2
spring.datasource.url=jdbc:h2:mem:vendasdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# 2. Configurações do Hibernate/JPA (A Mágica)
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# 3. Configuração da Interface Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
