spring.application.name=sistema-vendas

# 1. Configurações de Conexão com o Banco Postgres (Supabase, Session Pooler)
spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.mxeeagnqdhzkwhffdjrj
spring.datasource.password=${SUPABASE_DB_PASSWORD}

# 2. Configurações do Hibernate/JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true